version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0
  build:
    commands:
      - cd fanalarm/clientapp
      - npm install
      - cd ../../
      - dotnet restore
      - dotnet build
  post_build:
    commands:
      - dotnet publish -c Release -o ./publish

artifacts:
  files: ./publish/**
  discard-paths: yes

cache:
  paths:
    - ~/.nuget/packages
